# Base image with Node.js pre-installed
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/core-app

# Copy package.json and package-lock.json to the container
COPY core-app/package*.json ./

# Install dependencies
RUN npm ci

# Copy over all other files
COPY core-app/ .

# Build the React app
RUN npm run build

# Expose the container's port
EXPOSE 3001

# Set the command to start the app
CMD ["npm", "start"]
